name: HACS Validation
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: "integration"
          ignore: "brands"   # ignore default-listing brands check for now
      - name: Show manifest version
        run: |
          jq '.version' custom_components/smoothed_sensor/manifest.json || true
