name: Hassfest
on:
  push:
  pull_request:
jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hassfest
        uses: home-assistant/actions/hassfest@v2
